### ISSUE TITLE
notify schema.org people

### ISSUE THREAD

**Issue by VladimirAlexiev** [VladimirAlexiev/schema-datatypes#1]
Hi! here's the repo, and I put a simple README.
Please notify https://github.com/schemaorg/schemaorg/issues/1781 and maybe on twitter (I'm `@valexiev`) that we're looking for co-authors.

Next:
- I'll make a `paper.md` with some metadata
- What title did you propose?
- Should we use Zotero for refs? It will pay off if we have more than a few refs.

**Comment by jmkeil** [comment]
Lets take "Analysis of the Schema.org Datatypes Usage" as a working title. We might adapt it later, if the actual content is more clear.

I never used Zotero (I use JabRef). How do you add references in Markdown?
