### ISSUE TITLE
install zotero

### ISSUE THREAD

**Issue by VladimirAlexiev** [VladimirAlexiev/schema-datatypes#2]
https://www.zotero.org/download/
- install Zotero 
- install Chrome connector
- install Better Bibtex plugin
- register 
- join https://www.zotero.org/groups/4945365/pedantic_semantic_web (or give me your Zotero if you have problems joining)
- I've added the 3 refs from the 

> How do you add references in Markdown?

```
@aidanhoganWeavingPedanticWeb2010 states that...
... is very important [@aidanhoganWeavingPedanticWeb2010]
```

**Comment by jmkeil** [comment]
Will there be an bibtex file in the repo?

**Comment by VladimirAlexiev** [comment]
Yes, Better Bibtex installs a local server from we can get a good bibtex export it from Zotero using this Makefile:
```Makefile
BIBTEX:
	curl http://127.0.0.1:23119/better-bibtex/export/library?/3128934/library.biblatex -o bibliography.bib
```
(there's also https://retorque.re/zotero-better-bibtex/exporting/auto/ but I can't find this `Keep updated` option).

**Comment by jmkeil** [comment]
For the time being, I am not confinced regularly exporting a shared Zotero group into the repo is easier than just directly maintaining/syncing the bib with git, but it works for me now. I also found the `Keep updated` checkbox:
1. 
   ![zotero-keep-updated1](https://user-images.githubusercontent.com/16349846/220362601-32f184f0-4650-4a56-bdae-857f0be344d4.png)
2.
   ![zotero-keep-updated2](https://user-images.githubusercontent.com/16349846/220362895-3b6b3f1c-bdd3-4dea-8d52-e6fa89c31047.png)
